<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LQ1P5L8" failures="7" tests="10" name="Test" time="46.854" errors="0" timestamp="2025-01-22T12:56:00 IST">
  <testcase classname="utils.BaseTest" name="@BeforeMethod setUp" time="0.079">
    <failure type="org.openqa.selenium.remote.NoSuchDriverException" message="Unable to obtain: chromedriver, error chromedriver must exist: path\to\chromedriver
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/
Build info: version: &amp;apos;4.27.0&amp;apos;, revision: &amp;apos;d6e718d134&amp;apos;
System info: os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.1&amp;apos;
Driver info: driver.version: ChromeDriver">
      <![CDATA[org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: chromedriver, error chromedriver must exist: path\to\chromedriver
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.1'
Driver info: driver.version: ChromeDriver
at org.openqa.selenium.remote.service.DriverFinder.getBinaryPaths(DriverFinder.java:121)
at org.openqa.selenium.remote.service.DriverFinder.getDriverPath(DriverFinder.java:55)
at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:51)
at utils.BaseTest.setUp(BaseTest.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.IllegalStateException: chromedriver must exist: path\to\chromedriver
at org.openqa.selenium.internal.Require$PathStateChecker.isExecutable(Require.java:478)
at org.openqa.selenium.remote.service.DriverFinder.getBinaryPaths(DriverFinder.java:118)
... 36 more
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="utils.BaseTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="utils.BaseTest" name="@BeforeMethod setUp" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="utils.BaseTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="utils.BaseTest" name="@BeforeMethod setUp" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="utils.BaseTest" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="testcases.ForgotPasswordTest" name="testEmptyEmail" time="0.0">
    <skipped/>
  </testcase> <!-- testEmptyEmail -->
  <testcase classname="testcases.ForgotPasswordTest" name="testInvalidEmail" time="0.0">
    <skipped/>
  </testcase> <!-- testInvalidEmail -->
  <testcase classname="testcases.ForgotPasswordTest" name="testValidEmail" time="0.0">
    <skipped/>
  </testcase> <!-- testValidEmail -->
  <testcase classname="testcases.LoginTest" name="testInvalidLogin" time="5.746">
    <failure type="java.lang.AssertionError" message="Error message not displayed for invalid login! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message not displayed for invalid login! expected [true] but found [false]
at testcases.LoginTest.testInvalidLogin(LoginTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidLogin -->
  <testcase classname="testcases.LoginTest" name="testValidLogin" time="4.696">
    <failure type="java.lang.AssertionError" message="Login failed with valid credentials! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login failed with valid credentials! expected [true] but found [false]
at testcases.LoginTest.testValidLogin(LoginTest.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase classname="testcases.SignUpTest" name="testEmptyFirstName" time="5.124">
    <failure type="java.lang.AssertionError" message="Error message for empty first name is not displayed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message for empty first name is not displayed! expected [true] but found [false]
at testcases.SignUpTest.testEmptyFirstName(SignUpTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testEmptyFirstName -->
  <testcase classname="testcases.SignUpTest" name="testInvalidEmailFormat" time="3.259">
    <failure type="java.lang.AssertionError" message="Error message for invalid email format is not displayed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message for invalid email format is not displayed! expected [true] but found [false]
at testcases.SignUpTest.testInvalidEmailFormat(SignUpTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidEmailFormat -->
  <testcase classname="testcases.SignUpTest" name="testPasswordMismatch" time="8.176">
    <failure type="java.lang.AssertionError" message="Error message for password mismatch is not displayed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message for password mismatch is not displayed! expected [true] but found [false]
at testcases.SignUpTest.testPasswordMismatch(SignUpTest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testPasswordMismatch -->
  <testcase classname="testcases.SignUpTest" name="testSignUp" time="6.906">
    <failure type="java.lang.AssertionError" message="Sign-up failed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Sign-up failed! expected [true] but found [false]
at testcases.SignUpTest.testSignUp(SignUpTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testSignUp -->
  <testcase classname="testcases.SignUpTest" name="testWeakPassword" time="4.294">
    <failure type="java.lang.AssertionError" message="Error message for weak password is not displayed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message for weak password is not displayed! expected [true] but found [false]
at testcases.SignUpTest.testWeakPassword(SignUpTest.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testWeakPassword -->
</testsuite> <!-- Test -->
